# Generated by Django 5.0.6 on 2024-05-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Production', '0010_delete_brewingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewingEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50, verbose_name='Тип события')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.productionline', verbose_name='Производственная линия')),
            ],
        ),
    ]
