# Dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}/python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY .env /app/

COPY . /app/

EXPOSE 20000

CMD ["sh", "-c","python manage.py makemigrations --noinput && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py create_superuser && python manage.py loaddata production_line_data.json && python manage.py loaddata storage_data.json && python manage.py loaddata brewing_event_data.json && python manage.py loaddata CharacteristicProductionLine.json && python manage.py loaddata EmployeeData.json && python manage.py runserver 0.0.0.0:20000"]
