services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      cache_from:
        - pivoapi:latest
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: pivoapi
    container_name: PIVO_API
    ports:
      - "12345:20000"
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - django_static_volume:/app/static
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis
      - worker
    networks:
      - PIVO_API_Network


  db:
    image: postgres:13
    container_name: PIVO_API_DB
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - PIVO_API_Network

  redis:
    image: redis:6.2
    container_name: PIVO_redis
    volumes:
      - ./redis-data:/data
    networks:
      - PIVO_API_Network


  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      cache_from:
        - pivoapi:latest
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    container_name: PIVO_CELERY
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - PIVO_API_Network

volumes:
  django_static_volume:
  postgres_data:

networks:
  PIVO_API_Network:
      driver: bridge
