# Generated by Django 5.0.6 on 2024-05-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLinePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('performance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.productionline', verbose_name='Производительность производственной линии')),
            ],
        ),
    ]
