# Generated by Django 5.0.6 on 2024-05-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_storagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlineperformance',
            name='performance',
            field=models.DecimalField(decimal_places=3, help_text='Производительность в гектолитрах в час', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlineperformance',
            name='production_line',
            field=models.ForeignKey(help_text='Производительность производственной линии', on_delete=django.db.models.deletion.CASCADE, to='Production.productionline'),
        ),
        migrations.CreateModel(
            name='CharacteristicProductionLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operational_hours', models.IntegerField(help_text='Операционные часы в день')),
                ('maintenance_frequency', models.CharField(help_text='Частота технического обслуживания', max_length=100)),
                ('energy_consumption', models.FloatField(help_text='Потребление энергии в кВт·ч')),
                ('staff_required', models.IntegerField(help_text='Количество сотрудников, необходимых для работы линии')),
                ('downtime_per_month', models.FloatField(help_text='Время простоя в часах в месяц')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.productionline', verbose_name='Производственная линия')),
            ],
        ),
    ]
