# Generated by Django 5.0.6 on 2024-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_alter_productionlineperformance_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicproductionline',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
