# Generated by Django 5.0.6 on 2024-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_characteristicproductionline_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('production_line', models.CharField(max_length=100, verbose_name='Линия производства')),
            ],
        ),
        migrations.AddField(
            model_name='characteristicproductionline',
            name='efficiency',
            field=models.FloatField(default=0.0, help_text='Эффективность производственной линии'),
        ),
    ]
