# Generated by Django 5.0.6 on 2024-05-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0006_employee_characteristicproductionline_efficiency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
