# Generated by Django 5.0.6 on 2024-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicproductionline',
            name='status',
            field=models.CharField(default='', help_text='Статус линии', max_length=100),
        ),
    ]
