# Generated by Django 5.0.6 on 2024-05-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0008_characteristicproductionline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='production_line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Production.productionline', verbose_name='Производственная линия'),
        ),
    ]
