"""
Django settings for PIVO_API project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load parameters .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(&hkk#loxpk8t7xi)wxicj=sg3k6+77wiug4=698-2a3r&$%l&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'celery',
    'Production'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'PIVO_API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PIVO_API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_NAME'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'), 
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/app/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = ['*']

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

Q_CLUSTER = {
    'name': 'qcluster',
    'workers': 1,
    'queue_limit': 10,
    'timeout': 90,
    'etry': 120,
    'concurrency': 1,
    'chedule': 'Production.tasks.process_production_line_data', # имя функции и модуля
    'chedule_type': 'min', # тип расписания (min - каждую минуту)
    'chedule_time': '*', # время запуска (каждую минуту)
    'broker': 'PIVO_redis', # брокер сообщений
    'redis': 'redis://redis:6379/0', # конфигурация Redis
}

APPEND_SLASH = True

# CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOWED_ORIGINS = ['http://localhost:3000',  'https://beer.mishazx.ru', 'http://192.168.1.10:3000/', 'http://192.168.1.8:12346/']
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_ALLOW_ALL = False
# 4

# CORS_ALLOWED_ORIGINS = [
#     "https://beer.mishazx.ru/",
#     # "https://sub.example.com",
#     "http://localhost:3000/",
#     "http://127.0.0.1:3000/"
# ]

CSRF_TRUSTED_ORIGINS=['http://192.168.1.8:12346/','http://192.168.1.8:30000', 'https://api.beer.mishazx.ru', 'http://192.168.1.8:12345', 'http://localhost:3000', 'http://192.168.1.10:3000', 'http://192.168.1.8:3000', 'http://192.168.1.8:21000', 'https://www.mishazx.ru']

CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
# CORS_ORIGIN_WHITELIST = (
# # 5
#        'http://localhost:3000',
#        'http://127.0.0.1:3000',
#        'http://192.168.1.10:3000',
# )
# CORS_ALLOW_HEADERS = "*"

# CORS_ORIGIN_WHITELIST = (
# # 'http://example.com',
# 'http://127.0.0.1:3000',
# 'http://localhost:3000',
# )


# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# from corsheaders.defaults import default_headers
# CORS_ALLOW_HEADERS = list(default_headers) + [
#     'X-Amz-Date',
#     'Access-Control-Request-Headers',
#     'Access-Control-Allow-Headers',
#     'Access-Control-Allow-Origin',
#     'SameSite',
#     'XMLHttpRequest',
# ]

# CSRF_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SAMESITE = 'None'

# CSRF_COOKIE_DOMAIN = '.mishazx.ru'
# SESSION_COOKIE_DOMAIN = ".mishazx.ru"  # Or specify your domain

# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_HTTPONLY = True

# CSRF_TRUSTED_ORIGINS=['http://localhost:3000']
# CSRF_TRUSTED_ORIGINS=['http://192.168.1.8:30000', 'https://dev.iot.mishazx.ru', 'http://192.168.1.8:13000', 'http://localhost:3000', 'http://192.168.1.10:3000', 'http://192.168.1.8:3000', 'http://192.168.1.8:21000', 'https://www.mishazx.ru']

